# permissions for end users to edit objects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: object-editor-role
rules:
- apiGroups:
  - s3.aws.dev.nimak.link
  resources:
  - objects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.aws.dev.nimak.link
  resources:
  - objects/status
  verbs:
  - get
