apiVersion: s3.aws.dev.nimak.link/v1alpha1
kind: Object
metadata:
  name: object-sample
spec:
  deletionPolicy: delete
  target:
    region: us-west-2
    bucket: nk-sample-bucket
    key: scripts/code.txt
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-account-creds
      key: aws.creds
  source:
    data: |
      this is a sample file
      stored under s3://nk-sample-bucket/code.txt
